spring:
  profiles: ican
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: validate
    show-sql: true
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:./data/InAnalysis_db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

server.port: 8008

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.sql

management.security.enabled: false

logging:
  level:
    com.insnergy: DEBUG

in-analysis:
  csv-file-upload-directory: upload-dir
  python-server-url: http://ntuesoe.com:8002
  r-server-url: disable